extends RefCounted
## GENERATED by tools/process_rook_sprites.py — do not edit by hand.
## Rook sprite frames (assets/characters/rook/, 2x scale, 256x256, hero
## origin at (128, 248)) and each frame's near-shoulder pivot in 1x game
## units relative to the hero origin (facing right).

const TEXTURE_SCALE := 0.5
const CANVAS_OFFSET := Vector2(0, -120)  # canvas centre relative to the feet, 2x px

const SHOULDER := {
	&"idle_1": Vector2(-6.3, -75.4),
	&"idle_2": Vector2(-6.3, -75.1),
	&"run_1": Vector2(-6.3, -62.4),
	&"run_2": Vector2(-6.3, -52.4),
	&"run_3": Vector2(-6.3, -59.9),
	&"run_4": Vector2(-6.3, -67.8),
	&"run_5": Vector2(-6.3, -60.8),
	&"run_6": Vector2(-6.3, -62.2),
	&"jump_rise": Vector2(-6.3, -75.4),
	&"jump_fall": Vector2(-6.3, -75.4),
	&"land": Vector2(-6.3, -41.1),
	&"hurt": Vector2(-6.3, -64.5),
	&"defeated": Vector2(-6.3, -38.7),
	&"interact": Vector2(-6.3, -71.6),
}

## Arm texture: shoulder-cap centre in texture px (2x), and the fist
## relative to the shoulder in 1x game units (arm pointing right).
const ARM_SHOULDER_PX := Vector2(10.8, 14.6)
const ARM_FIST := Vector2(34.5, 2.1)
