extends RefCounted
## GENERATED by tools/process_elevenlabs.py from the ElevenLabs takes under
## audio-source/elevenlabs/ (N05). Do not edit by hand; rerun the tool.
## The Audio director plays a cue from `SFX` when it has an entry whose files load,
## and falls back to the cue's old source in SFX_SOURCES otherwise. `volume_db` is
## each entry's mix trim (the files are levelled per cue, see the tool's docstring).
## No `class_name` (the project's import-cache rule): the director preloads it by path.

const SFX := {
	&"adam_chime": {"files": ["res://assets/audio/eleven/sfx/adam_chime_1.wav", "res://assets/audio/eleven/sfx/adam_chime_2.wav"], "volume_db": -2.5},
	&"alarm": {"files": ["res://assets/audio/eleven/sfx/alarm_1.wav", "res://assets/audio/eleven/sfx/alarm_2.wav"], "volume_db": -6.5},
	&"bark_guard_dont_make_me": {"files": ["res://assets/audio/eleven/sfx/bark_guard_dont_make_me_1.wav", "res://assets/audio/eleven/sfx/bark_guard_dont_make_me_2.wav"], "volume_db": -5.5},
	&"bark_guard_ground": {"files": ["res://assets/audio/eleven/sfx/bark_guard_ground_1.wav", "res://assets/audio/eleven/sfx/bark_guard_ground_2.wav"], "volume_db": -5.5},
	&"bark_guard_hes_shooting": {"files": ["res://assets/audio/eleven/sfx/bark_guard_hes_shooting_1.wav", "res://assets/audio/eleven/sfx/bark_guard_hes_shooting_2.wav"], "volume_db": -5.5},
	&"bark_guard_last_warning": {"files": ["res://assets/audio/eleven/sfx/bark_guard_last_warning_1.wav", "res://assets/audio/eleven/sfx/bark_guard_last_warning_2.wav"], "volume_db": -5.5},
	&"bark_guard_security": {"files": ["res://assets/audio/eleven/sfx/bark_guard_security_1.wav", "res://assets/audio/eleven/sfx/bark_guard_security_2.wav"], "volume_db": -5.5},
	&"bark_guard_shots_fired": {"files": ["res://assets/audio/eleven/sfx/bark_guard_shots_fired_1.wav", "res://assets/audio/eleven/sfx/bark_guard_shots_fired_2.wav"], "volume_db": -5.5},
	&"bark_guard_there_he_is": {"files": ["res://assets/audio/eleven/sfx/bark_guard_there_he_is_1.wav", "res://assets/audio/eleven/sfx/bark_guard_there_he_is_2.wav"], "volume_db": -5.5},
	&"bark_staffer_dave": {"files": ["res://assets/audio/eleven/sfx/bark_staffer_dave_1.wav", "res://assets/audio/eleven/sfx/bark_staffer_dave_2.wav"], "volume_db": -3.5},
	&"bark_staffer_hold_still": {"files": ["res://assets/audio/eleven/sfx/bark_staffer_hold_still_1.wav", "res://assets/audio/eleven/sfx/bark_staffer_hold_still_2.wav"], "volume_db": -2.5},
	&"bark_staffer_stay": {"files": ["res://assets/audio/eleven/sfx/bark_staffer_stay_1.wav", "res://assets/audio/eleven/sfx/bark_staffer_stay_2.wav"], "volume_db": -2.5},
	&"bark_staffer_workstation": {"files": ["res://assets/audio/eleven/sfx/bark_staffer_workstation_1.wav", "res://assets/audio/eleven/sfx/bark_staffer_workstation_2.wav"], "volume_db": -2.5},
	&"body_fall": {"files": ["res://assets/audio/eleven/sfx/body_fall_1.wav", "res://assets/audio/eleven/sfx/body_fall_2.wav", "res://assets/audio/eleven/sfx/body_fall_3.wav", "res://assets/audio/eleven/sfx/body_fall_4.wav"], "volume_db": -7.5},
	&"bolt_blocked": {"files": ["res://assets/audio/eleven/sfx/bolt_blocked_1.wav", "res://assets/audio/eleven/sfx/bolt_blocked_2.wav", "res://assets/audio/eleven/sfx/bolt_blocked_3.wav"], "volume_db": -2.5},
	&"bolt_hit": {"files": ["res://assets/audio/eleven/sfx/bolt_hit_1.wav", "res://assets/audio/eleven/sfx/bolt_hit_2.wav", "res://assets/audio/eleven/sfx/bolt_hit_3.wav"], "volume_db": -8.5},
	&"cache_open": {"files": ["res://assets/audio/eleven/sfx/cache_open_1.wav", "res://assets/audio/eleven/sfx/cache_open_2.wav"], "volume_db": -8.5},
	&"checkpoint": {"files": ["res://assets/audio/eleven/sfx/checkpoint_1.wav", "res://assets/audio/eleven/sfx/checkpoint_2.wav"], "volume_db": -6.5},
	&"chip": {"files": ["res://assets/audio/eleven/sfx/chip_1.wav", "res://assets/audio/eleven/sfx/chip_2.wav", "res://assets/audio/eleven/sfx/chip_3.wav"], "volume_db": -10.5},
	&"chip_cluster": {"files": ["res://assets/audio/eleven/sfx/chip_cluster_1.wav", "res://assets/audio/eleven/sfx/chip_cluster_2.wav"], "volume_db": -8.5},
	&"debris_clatter": {"files": ["res://assets/audio/eleven/sfx/debris_clatter_1.wav", "res://assets/audio/eleven/sfx/debris_clatter_2.wav"], "volume_db": -12.5},
	&"door_unlock": {"files": ["res://assets/audio/eleven/sfx/door_unlock_1.wav", "res://assets/audio/eleven/sfx/door_unlock_2.wav"], "volume_db": -5.5},
	&"evidence": {"files": ["res://assets/audio/eleven/sfx/evidence_1.wav", "res://assets/audio/eleven/sfx/evidence_2.wav"], "volume_db": -4.5},
	&"exit": {"files": ["res://assets/audio/eleven/sfx/exit_1.wav", "res://assets/audio/eleven/sfx/exit_2.wav"], "volume_db": -0.5},
	&"footstep_metal": {"files": ["res://assets/audio/eleven/sfx/footstep_metal_1.wav", "res://assets/audio/eleven/sfx/footstep_metal_2.wav", "res://assets/audio/eleven/sfx/footstep_metal_3.wav", "res://assets/audio/eleven/sfx/footstep_metal_4.wav"], "volume_db": -18.5},
	&"footstep_paving": {"files": ["res://assets/audio/eleven/sfx/footstep_paving_1.wav", "res://assets/audio/eleven/sfx/footstep_paving_2.wav", "res://assets/audio/eleven/sfx/footstep_paving_3.wav", "res://assets/audio/eleven/sfx/footstep_paving_4.wav"], "volume_db": -18.5},
	&"footstep_roof": {"files": ["res://assets/audio/eleven/sfx/footstep_roof_1.wav", "res://assets/audio/eleven/sfx/footstep_roof_2.wav", "res://assets/audio/eleven/sfx/footstep_roof_3.wav", "res://assets/audio/eleven/sfx/footstep_roof_4.wav"], "volume_db": -20.5},
	&"guard_swing": {"files": ["res://assets/audio/eleven/sfx/guard_swing_1.wav", "res://assets/audio/eleven/sfx/guard_swing_2.wav", "res://assets/audio/eleven/sfx/guard_swing_3.wav", "res://assets/audio/eleven/sfx/guard_swing_4.wav"], "volume_db": -4.5},
	&"guard_windup": {"files": ["res://assets/audio/eleven/sfx/guard_windup_1.wav", "res://assets/audio/eleven/sfx/guard_windup_2.wav", "res://assets/audio/eleven/sfx/guard_windup_3.wav", "res://assets/audio/eleven/sfx/guard_windup_4.wav"], "volume_db": -3.5},
	&"hatch_open": {"files": ["res://assets/audio/eleven/sfx/hatch_open_1.wav", "res://assets/audio/eleven/sfx/hatch_open_2.wav"], "volume_db": -5.5},
	&"hero_hurt": {"files": ["res://assets/audio/eleven/sfx/hero_hurt_1.wav", "res://assets/audio/eleven/sfx/hero_hurt_2.wav", "res://assets/audio/eleven/sfx/hero_hurt_3.wav", "res://assets/audio/eleven/sfx/hero_hurt_4.wav"], "volume_db": -6.5},
	&"hero_jump": {"files": ["res://assets/audio/eleven/sfx/hero_jump_1.wav", "res://assets/audio/eleven/sfx/hero_jump_2.wav", "res://assets/audio/eleven/sfx/hero_jump_3.wav", "res://assets/audio/eleven/sfx/hero_jump_4.wav"], "volume_db": -12.5},
	&"hero_land": {"files": ["res://assets/audio/eleven/sfx/hero_land_1.wav", "res://assets/audio/eleven/sfx/hero_land_2.wav", "res://assets/audio/eleven/sfx/hero_land_3.wav", "res://assets/audio/eleven/sfx/hero_land_4.wav"], "volume_db": -10.5},
	&"hit_flesh": {"files": ["res://assets/audio/eleven/sfx/hit_flesh_1.wav", "res://assets/audio/eleven/sfx/hit_flesh_2.wav", "res://assets/audio/eleven/sfx/hit_flesh_3.wav", "res://assets/audio/eleven/sfx/hit_flesh_4.wav"], "volume_db": -7.5},
	&"interact": {"files": ["res://assets/audio/eleven/sfx/interact_1.wav", "res://assets/audio/eleven/sfx/interact_2.wav"], "volume_db": -10.5},
	&"keycard": {"files": ["res://assets/audio/eleven/sfx/keycard_1.wav", "res://assets/audio/eleven/sfx/keycard_2.wav"], "volume_db": -6.5},
	&"keycard_denied": {"files": ["res://assets/audio/eleven/sfx/keycard_denied_1.wav", "res://assets/audio/eleven/sfx/keycard_denied_2.wav"], "volume_db": -8.5},
	&"latch": {"files": ["res://assets/audio/eleven/sfx/latch_1.wav", "res://assets/audio/eleven/sfx/latch_2.wav"], "volume_db": -8.5},
	&"link_chirp": {"files": ["res://assets/audio/eleven/sfx/link_chirp_1.wav", "res://assets/audio/eleven/sfx/link_chirp_2.wav"], "volume_db": -10.5},
	&"lockdown": {"files": ["res://assets/audio/eleven/sfx/lockdown_1.wav", "res://assets/audio/eleven/sfx/lockdown_2.wav"], "volume_db": -2.5},
	&"med_patch": {"files": ["res://assets/audio/eleven/sfx/med_patch_1.wav", "res://assets/audio/eleven/sfx/med_patch_2.wav"], "volume_db": -8.5},
	&"pistol_fire": {"files": ["res://assets/audio/eleven/sfx/pistol_fire_1.wav", "res://assets/audio/eleven/sfx/pistol_fire_2.wav", "res://assets/audio/eleven/sfx/pistol_fire_3.wav"], "volume_db": -1.5},
	&"pistol_fire_quick": {"files": ["res://assets/audio/eleven/sfx/pistol_fire_quick_1.wav", "res://assets/audio/eleven/sfx/pistol_fire_quick_2.wav", "res://assets/audio/eleven/sfx/pistol_fire_quick_3.wav"], "volume_db": -2.5},
	&"pit_fall": {"files": ["res://assets/audio/eleven/sfx/pit_fall_1.wav", "res://assets/audio/eleven/sfx/pit_fall_2.wav"], "volume_db": -6.5},
	&"purchase": {"files": ["res://assets/audio/eleven/sfx/purchase_1.wav", "res://assets/audio/eleven/sfx/purchase_2.wav"], "volume_db": -8.5},
	&"ready_click": {"files": ["res://assets/audio/eleven/sfx/ready_click_1.wav", "res://assets/audio/eleven/sfx/ready_click_2.wav"], "volume_db": -12.5},
	&"rover_armor": {"files": ["res://assets/audio/eleven/sfx/rover_armor_1.wav", "res://assets/audio/eleven/sfx/rover_armor_2.wav"], "volume_db": -5.5},
	&"rover_charge": {"files": ["res://assets/audio/eleven/sfx/rover_charge_1.wav", "res://assets/audio/eleven/sfx/rover_charge_2.wav"], "volume_db": -2.5},
	&"rover_destroyed": {"files": ["res://assets/audio/eleven/sfx/rover_destroyed_1.wav", "res://assets/audio/eleven/sfx/rover_destroyed_2.wav"], "volume_db": -1.5},
	&"rover_patrol": {"files": ["res://assets/audio/eleven/sfx/rover_patrol_1.wav", "res://assets/audio/eleven/sfx/rover_patrol_2.wav"], "volume_db": -14.5},
	&"rover_stall": {"files": ["res://assets/audio/eleven/sfx/rover_stall_1.wav", "res://assets/audio/eleven/sfx/rover_stall_2.wav"], "volume_db": -2.5},
	&"rover_windup": {"files": ["res://assets/audio/eleven/sfx/rover_windup_1.wav", "res://assets/audio/eleven/sfx/rover_windup_2.wav"], "volume_db": -3.5},
	&"save_failed": {"files": ["res://assets/audio/eleven/sfx/save_failed_1.wav", "res://assets/audio/eleven/sfx/save_failed_2.wav"], "volume_db": -7.5},
	&"staffer_defeat": {"files": ["res://assets/audio/eleven/sfx/staffer_defeat_1.wav", "res://assets/audio/eleven/sfx/staffer_defeat_2.wav", "res://assets/audio/eleven/sfx/staffer_defeat_3.wav"], "volume_db": -4.5},
	&"staffer_lunge": {"files": ["res://assets/audio/eleven/sfx/staffer_lunge_1.wav", "res://assets/audio/eleven/sfx/staffer_lunge_2.wav"], "volume_db": -5.5},
	&"staffer_windup": {"files": ["res://assets/audio/eleven/sfx/staffer_windup_1.wav", "res://assets/audio/eleven/sfx/staffer_windup_2.wav", "res://assets/audio/eleven/sfx/staffer_windup_3.wav"], "volume_db": -3.5},
	&"sting_checkpoint": {"files": ["res://assets/audio/eleven/music/sting_checkpoint.wav"], "volume_db": -7.5},
	&"sting_complete": {"files": ["res://assets/audio/eleven/music/sting_complete.wav"], "volume_db": -3.5},
	&"swap": {"files": ["res://assets/audio/eleven/sfx/swap_1.wav", "res://assets/audio/eleven/sfx/swap_2.wav"], "volume_db": -10.5},
	&"toast_save": {"files": ["res://assets/audio/eleven/sfx/toast_save_1.wav", "res://assets/audio/eleven/sfx/toast_save_2.wav"], "volume_db": -12.5},
	&"ui_back": {"files": ["res://assets/audio/eleven/sfx/ui_back_1.wav", "res://assets/audio/eleven/sfx/ui_back_2.wav"], "volume_db": -11.5},
	&"ui_confirm": {"files": ["res://assets/audio/eleven/sfx/ui_confirm_1.wav", "res://assets/audio/eleven/sfx/ui_confirm_2.wav"], "volume_db": -11.5},
	&"ui_move": {"files": ["res://assets/audio/eleven/sfx/ui_move_1.wav", "res://assets/audio/eleven/sfx/ui_move_2.wav", "res://assets/audio/eleven/sfx/ui_move_3.wav"], "volume_db": -16.5},
	&"ui_pause": {"files": ["res://assets/audio/eleven/sfx/ui_pause_1.wav", "res://assets/audio/eleven/sfx/ui_pause_2.wav"], "volume_db": -11.5},
	&"uplink": {"files": ["res://assets/audio/eleven/sfx/uplink_1.wav", "res://assets/audio/eleven/sfx/uplink_2.wav", "res://assets/audio/eleven/sfx/uplink_3.wav"], "volume_db": -16.5},
}

## Seamless loops, one file each, played by Audio.set_ambience().
const AMBIENCE := {
	&"amb_alarm_far": {"file": "res://assets/audio/eleven/amb/amb_alarm_far.wav", "volume_db": -23.6},
	&"amb_campus_night": {"file": "res://assets/audio/eleven/amb/amb_campus_night.wav", "volume_db": -16.7},
	&"amb_depot_hum": {"file": "res://assets/audio/eleven/amb/amb_depot_hum.wav", "volume_db": -16.2},
	&"amb_lockdown_bed": {"file": "res://assets/audio/eleven/amb/amb_lockdown_bed.wav", "volume_db": 0.0},
	&"amb_plaza_wet": {"file": "res://assets/audio/eleven/amb/amb_plaza_wet.wav", "volume_db": -1.4},
	&"amb_roof_night": {"file": "res://assets/audio/eleven/amb/amb_roof_night.wav", "volume_db": -13.2},
	&"amb_server_core": {"file": "res://assets/audio/eleven/amb/amb_server_core.wav", "volume_db": -4.9},
	&"amb_wicket_yard": {"file": "res://assets/audio/eleven/amb/amb_wicket_yard.wav", "volume_db": -11.1},
}

## Spoken lines, played by Audio.play_voice(); several files are alternate takes.
const VOICE := {
	&"adam_hello": {"files": ["res://assets/audio/eleven/voice/adam_hello_1.wav", "res://assets/audio/eleven/voice/adam_hello_2.wav"], "volume_db": -2.5},
	&"adam_stay": {"files": ["res://assets/audio/eleven/voice/adam_stay_1.wav", "res://assets/audio/eleven/voice/adam_stay_2.wav"], "volume_db": -2.5},
	&"dave_word_gets_around": {"files": ["res://assets/audio/eleven/voice/dave_word_gets_around_1.wav", "res://assets/audio/eleven/voice/dave_word_gets_around_2.wav"], "volume_db": -3.5},
	&"pa_lethal": {"files": ["res://assets/audio/eleven/voice/pa_lethal_1.wav"], "volume_db": -4.5},
	&"pa_remain_calm": {"files": ["res://assets/audio/eleven/voice/pa_remain_calm_1.wav", "res://assets/audio/eleven/voice/pa_remain_calm_2.wav"], "volume_db": -4.5},
}

## Music loops, one stereo file each (levelled to the old synthesized loops), played by
## Audio.set_music(); a track here replaces the synthesized loop of the same key.
const MUSIC := {
	&"campus": {"file": "res://assets/audio/eleven/music/campus.wav", "volume_db": 0.0},
	&"depot": {"file": "res://assets/audio/eleven/music/depot.wav", "volume_db": 0.0},
	&"lockdown": {"file": "res://assets/audio/eleven/music/lockdown.wav", "volume_db": 0.0},
	&"title": {"file": "res://assets/audio/eleven/music/title.wav", "volume_db": 0.0},
}
